### ISSUE TITLE
segmentByCBS(): Add argument 'avg'

### ISSUE THREAD

**Issue by HenrikBengtsson** [HenrikBengtsson/PSCBS#16]
Add support for `segmentByCBS(..., avg="median")` analogously to `avgTCN` and `avgDH` for `segmentByPairedPSCBS()`.  The effect is that the segment-mean levels are re-calculated post segmentation using the 'median' rather that the default (sample) `mean` estimator.

**Comment by etal** [comment]
Relatedly: When segmentation is performed with weights on each probe, the segment means are calculated with an unweighted mean. If the weights vary wildly, then the resulting segment means can be a poor fit for the data.

I was about to file that as a separate bug, but I think it can be consolidated here as another option to `avg`, e.g. `avg="weighted"`. Does that seem sensible?

See also: https://github.com/etal/cnvkit/issues/28#issuecomment-103406993

Tangentially: Either DNAcopy or PSCBS seems to be excluding some probes from the segment mean calculation even without first "smoothing" the data. Do you know how/why this is happening, or if I'm mistaken?

**Comment by HenrikBengtsson** [comment]
@etal, bumped up your comment to a separate bug report #18.

**Comment by HenrikBengtsson** [comment]
Currently, median levels can be achieved as:
```r
fit <- segmentByCBS(...)
fit <- updateMeans(fit, avg="median")
```
