### ISSUE TITLE
segmentByCBS(..., w=...): Resulting mean levels are calculated without using weights 'w'

### ISSUE THREAD

**Issue by HenrikBengtsson** [HenrikBengtsson/PSCBS#18]
Moved from Issue #16 and comment by @etal:

> Relatedly: When segmentation is performed with weights on each probe, the segment means are calculated with an unweighted mean. If the weights vary wildly, then the resulting segment means can be a poor fit for the data.
> 
> I was about to file that as a separate bug, but I think it can be consolidated here as another option to `avg`, e.g. `avg="weighted"`. Does that seem sensible?
> 
> See also: https://github.com/etal/cnvkit/issues/28#issuecomment-103406993

**Comment by HenrikBengtsson** [comment]
A troubleshooting note: The [`updateMeans()` method for `CBS`](https://github.com/HenrikBengtsson/PSCBS/blob/master/R/CBS.R#L449-L568) objects at least have code prepared for this (my memory is so bad so I don't know when I did this):
```r
  hasWeights <- !is.null(w);
...
  if (hasWeights) {
    if(avg == "mean") {
      avgFUN <- weighted.mean;
    } else if(avg == "median") {
      avgFUN <- weightedMedian;
    } else {
      throw("Value of argument 'avg' is not supported with weights: ", avg);
    }
  } else {
    avgFUN <- get(avg, mode="function");
  }
...
    # (d) Update mean
    if (hasWeights) {
      wSS <- wSS / sum(wSS);
      gamma <- avgFUN(ySS, w=wSS);
    } else {
      gamma <- avgFUN(ySS);
    }
...
```

ACTIONS:
1. Write package test assert that weighted averages are returned.
2. See if calling `fit <- updateMeans(fit)` solved the problem; if so, then figure out why that is not done automatically.

**Comment by HenrikBengtsson** [comment]
@etal, it turns out that there wasn't an issue with how the mean level was calculated, but instead that _weights were ignored/lost if more than one chromosome were segmented_  effectively making it like you called `segmentByCBS()` without the weight argument `w`.  The only time it worked was for segmentations of a single chromosome.

I have fixed this bug in the [develop](https://github.com/HenrikBengtsson/PSCBS/tree/develop) branch, which for now can be installed as:
```r
source("http://callr.org/install#HenrikBengtsson/PSCBS@develop")
```

I've added a [package test script](https://github.com/HenrikBengtsson/PSCBS/blob/develop/tests/segmentByCBS%2Cweights.R) that asserts (visually and numerically) that weights are now being used.

**Comment by HenrikBengtsson** [comment]
@etal, let me know if this solves the problem behind etal/cnvkit#28 or if there is more to that one that has to do with PSCBS.

I'm closing this particular issue now.

**Comment by etal** [comment]
Thanks! I trust the test script; I'll try it out in PS mode and see if it works there too.

CNVkit currently has a post-processing step to ensure the segments behave well:
https://github.com/etal/cnvkit/blob/master/cnvlib/segmentation/__init__.py#L106

**Comment by HenrikBengtsson** [comment]
Not sure I understand the need for `repair_segments()` in CNVkit, but if you think part of it should be in the PSCBS package, let me know.
