### ISSUE TITLE
"Normal contamination": Argument for promoting our "secret" estimateKappa()

### ISSUE THREAD

**Issue by HenrikBengtsson** [HenrikBengtsson/PSCBS#44]
In PSCBS there's `estimateKappa()` which estimates "global background in segmented copy numbers".  We have on purpose avoided claiming this is an estimate of the amount of 'normal contamination' in the sample, where the reason is that we say the kappa estimate is a function of normal contamination, _but it may also be more_.  We simply don't know whether the dominant component is normal contamination or not - if it is, we probably would promote the estimate a bit more.  A formal study would help us figure that out.  However, we do say that it's likely that if the estimated kappa is larger in one sample than another, then we also believe that the normal contamination is larger too.  (This somewhat suggests that normal contamination is dominant).

Today I had a meeting where the amount of normal contamination turns out to be decent indicator for quality of other downstream estimates.  In other words, estimating kappa and comparing across samples is probably a very useful QC metric in multi-sample studies.  Because of this, I think PSCBS should try to bring the kappa estimator forward beyond the mentioning in [one of the vignette](https://cran.r-project.org/web/packages/PSCBS/vignettes/PairedPSCBS.pdf).

@pneuvial, what do you think?

**Comment by pneuvial** [comment]
Yes I believe it's a very good idea. Promoting it can help us to know whether it can actually be useful in practice... and motivate the formal study you are referring to.  It may also help clarifying whether/when it's "only" a quantitative indicator correlated to normal contamination, or a proper estimator.

**Comment by HenrikBengtsson** [comment]
ACTION:
* [ ] Report estimated kappa in PSCBS reports

**Comment by HenrikBengtsson** [comment]
UPDATE 2019-05-04: In the next release, `report()` on Paired PSCBS results will include the following subsection under 'Whole-Genome Results':

## Normal contamination

The estimated amount of normal contamination of this sample is 34.2% (κ = 0.342). This estimate, which is provided due to popular demand, is also affected by other types of background signals, which may be specific to sample or batch. Because of this, great care should be taken when interpreting this estimate and using it in downstream analysis. Being conservative, we recommend to not to use it as an accurate estimate of the true amount of normal contamination. However, if the sample and batch-specific effects are small, estimates from multiple samples may compared with each other, i.e. samples can be ranked by their relative amount of normal contamination (which might be done also when the absolute values cannot be trusted).

... let's see how that goes.
