### ISSUE TITLE
New CRAN release before Bioc 3.8

### ISSUE THREAD

**Issue by lima1** [HenrikBengtsson/PSCBS#48]
The avoidance of gc() in https://github.com/HenrikBengtsson/PSCBS/blob/develop/NEWS#L12-L13 reduces the R CMD check runtime of one of my packages by a couple of minutes. Is it possible to make a new release before the next Bioconductor release?

Thanks a lot,
Markus

**Comment by HenrikBengtsson** [comment]
Yes, I should be able to roll out PSCBS on CRAN before the next Bioc release. When is it?

**Comment by lima1** [comment]
Not in a while, usually mid October to early November.

**Comment by lima1** [comment]
Thanks for looking it this.

On my Macbook the devel version seems to be much faster:

```
Examples with CPU or elapsed time > 5s
                    user system elapsed
segmentationPSCBS 32.588  0.672  34.036
runAbsoluteCN     24.571  0.303  21.574
filterIntervals   18.108  0.299  17.124
segmentationCBS   14.809  0.196  13.355
findFocal         14.669  0.188  13.246
annotateTargets    7.006  0.650   8.750
```

```
Examples with CPU or elapsed time > 5s
                     user system elapsed
segmentationPSCBS 104.262  0.572 103.430
runAbsoluteCN      24.235  0.283  21.105
filterIntervals    19.096  0.455  18.697
findFocal          16.780  0.388  15.974
segmentationCBS    15.029  0.173  13.419
annotateTargets     6.281  0.380   7.257
```

**Comment by HenrikBengtsson** [comment]
Wow, but on the other hand, it makes sense if there are lots of segments - we basically got one `gc()` call per segment, which really adds up.

**Comment by HenrikBengtsson** [comment]
PSCBS 0.64.0 is now on CRAN.
