### ISSUE TITLE
Strange CBS failure with no calls for an entire chromosome

### ISSUE THREAD

**Issue by arostamianfar** [HenrikBengtsson/PSCBS#53]
There seems to be an issue with CBS that returns no calls (i.e. one region) for an entire chromosome for a particular input. The strange thing is that **slightly changing the weight of one of the rows (from `0.49` to `0.59`) suddenly results in over 27 regions (expected output)**.

I've attached the file that is causing the issue. If the very last row is removed or its weight is slightly increased, then 27 regions are outputted. Note that there are over 29k rows in the input, so a drastic change in CBS output based on a slight change in one of the rows seems like a bug. The same issue continues to happen if more rows are added to the end of the file.

We're using CBS through [CNVkit](https://github.com/etal/cnvkit/blob/1359013f8ab3a555ba51683d1168d8fe0f805f28/cnvlib/segmentation/cbs.py), but the issue can be reproduced directly from R. We're using version `0.65.0`.
```
> library('DNAcopy')
> tbl = read.delim("failing.cnr.txt")
> cna = CNA(cbind(tbl$log2), tbl$chromosome, tbl$start, data.type="logratio", presorted=T)
> fit = segment(cna, weights=tbl$weight, alpha=0.001)
> fit
Call:
segment(x = cna, weights = tbl$weight, alpha = 0.001)

        ID chrom loc.start  loc.end num.mark seg.mean
1 Sample.1     1     10000 25654941    24931  -0.0131
```
Changing the last row's weight to `0.59` results in:
```
> fit
Call:
segment(x = cna, weights = tbl$weight, alpha = 0.001)

         ID chrom loc.start  loc.end num.mark seg.mean
1  Sample.1     1     10000    44084       35   0.1706
2  Sample.1     1     45087    94209       36   0.5218
3  Sample.1     1     95212   127292       33  -0.0349
4  Sample.1     1    128294   176414       49   0.1657
5  Sample.1     1    227417   328693       52  -0.3876
....
```

Input file:
[failing.cnr.txt](https://github.com/HenrikBengtsson/PSCBS/files/3532247/failing.cnr.txt)

**Comment by HenrikBengtsson** [comment]
Looks like https://github.com/veseshan/DNAcopy/issues is better suited for this question.

**Comment by arostamianfar** [comment]
Thanks, @HenrikBengtsson . I'll see if I can reproduce this bug with a smaller subset and will post in DNAcopy.
